frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

new_com:
    path:    /new/comment/{id}
    defaults: { _controller: CommentaireBundle:Default:newcom }

post_com:
    path:    /post/comment/{id}
    defaults: { _controller: CommentaireBundle:Default:postcom }